{% set version = "0.2.0" %}

package:
  name: dask-geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/dask-geopandas/releases/download/v{{ version }}/dask-geopandas-{{ version }}.tar.gz
  sha256: 8ed7c55574ae5274217251122cf2b0c5211208a4c786a77bcd3fed437bd90641

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - geopandas-base >=0.10
    - dask-core >=2021.06.0
    - pygeos
    - packaging

test:
  imports:
    - dask_geopandas

about:
  home: https://github.com/geopandas/dask-geopandas
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Parallel GeoPandas with Dask

extra:
  recipe-maintainers:
    - martinfleis
    - jorisvandenbossche
    - jsignell
